github:
  - roohithbala
patreon: your-patreon-username
open_collective: your-open-collective-username
ko_fi: your-kofi-username
tidelift: your-tidelift-platform
community_bridge: your-community-bridge-project
liberapay: your-liberapay-username
issuehunt: your-issuehunt-username
lfx_crowdfunding: your-lfx-crowdfunding-project
polar: your-polar-username
buy_me_a_coffee: your-buymeacoffee-username
thanks_dev: your-thanksdev-username
custom:
  - https://example.com/donate1
  - https://example.com/donate2
